In [ ]:
#case1
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.599544
>> Epoch 2 finished 	RBM Reconstruction error 42.976945
>> Epoch 3 finished 	RBM Reconstruction error 42.911898
>> Epoch 4 finished 	RBM Reconstruction error 42.992147
>> Epoch 5 finished 	RBM Reconstruction error 43.180143
>> Epoch 6 finished 	RBM Reconstruction error 43.271735
>> Epoch 7 finished 	RBM Reconstruction error 43.482608
>> Epoch 8 finished 	RBM Reconstruction error 43.651730
>> Epoch 9 finished 	RBM Reconstruction error 44.033955
>> Epoch 10 finished 	RBM Reconstruction error 43.820545
>> Epoch 1 finished 	RBM Reconstruction error 9.997884
>> Epoch 2 finished 	RBM Reconstruction error 6.580758
>> Epoch 3 finished 	RBM Reconstruction error 5.279427
>> Epoch 4 finished 	RBM Reconstruction error 4.759158
>> Epoch 5 finished 	RBM Reconstruction error 4.508030
>> Epoch 6 finished 	RBM Reconstruction error 4.248742
>> Epoch 7 finished 	RBM Reconstruction error 4.053245
>> Epoch 8 finished 	RBM Re

In [ ]:
#case2
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.782150
>> Epoch 2 finished 	RBM Reconstruction error 42.928241
>> Epoch 3 finished 	RBM Reconstruction error 42.655945
>> Epoch 4 finished 	RBM Reconstruction error 42.693698
>> Epoch 5 finished 	RBM Reconstruction error 42.927321
>> Epoch 6 finished 	RBM Reconstruction error 43.209267
>> Epoch 7 finished 	RBM Reconstruction error 43.481772
>> Epoch 8 finished 	RBM Reconstruction error 43.672546
>> Epoch 9 finished 	RBM Reconstruction error 44.062125
>> Epoch 10 finished 	RBM Reconstruction error 43.818609
>> Epoch 1 finished 	RBM Reconstruction error 10.392400
>> Epoch 2 finished 	RBM Reconstruction error 6.700058
>> Epoch 3 finished 	RBM Reconstruction error 5.298466
>> Epoch 4 finished 	RBM Reconstruction error 4.796281
>> Epoch 5 finished 	RBM Reconstruction error 4.568461
>> Epoch 6 finished 	RBM Reconstruction error 4.397188
>> Epoch 7 finished 	RBM Reconstruction error 4.223192
>> Epoch 8 finished 	RBM R

In [ ]:
#case3
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.579861
>> Epoch 2 finished 	RBM Reconstruction error 42.648378
>> Epoch 3 finished 	RBM Reconstruction error 42.461308
>> Epoch 4 finished 	RBM Reconstruction error 42.441174
>> Epoch 5 finished 	RBM Reconstruction error 42.601003
>> Epoch 6 finished 	RBM Reconstruction error 42.680919
>> Epoch 7 finished 	RBM Reconstruction error 42.801097
>> Epoch 8 finished 	RBM Reconstruction error 42.832580
>> Epoch 9 finished 	RBM Reconstruction error 43.133236
>> Epoch 10 finished 	RBM Reconstruction error 42.917262
>> Epoch 1 finished 	RBM Reconstruction error 10.114342
>> Epoch 2 finished 	RBM Reconstruction error 6.303115
>> Epoch 3 finished 	RBM Reconstruction error 5.110419
>> Epoch 4 finished 	RBM Reconstruction error 4.639163
>> Epoch 5 finished 	RBM Reconstruction error 4.457079
>> Epoch 6 finished 	RBM Reconstruction error 4.256772
>> Epoch 7 finished 	RBM Reconstruction error 4.115946
>> Epoch 8 finished 	RBM R

In [ ]:
#case4
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.815052
>> Epoch 2 finished 	RBM Reconstruction error 40.867323
>> Epoch 3 finished 	RBM Reconstruction error 40.931374
>> Epoch 4 finished 	RBM Reconstruction error 41.054906
>> Epoch 5 finished 	RBM Reconstruction error 41.300267
>> Epoch 6 finished 	RBM Reconstruction error 41.585167
>> Epoch 7 finished 	RBM Reconstruction error 41.854288
>> Epoch 8 finished 	RBM Reconstruction error 42.041261
>> Epoch 9 finished 	RBM Reconstruction error 42.439653
>> Epoch 10 finished 	RBM Reconstruction error 42.228696
>> Epoch 1 finished 	RBM Reconstruction error 14.240275
>> Epoch 2 finished 	RBM Reconstruction error 11.222238
>> Epoch 3 finished 	RBM Reconstruction error 10.207335
>> Epoch 4 finished 	RBM Reconstruction error 9.561489
>> Epoch 5 finished 	RBM Reconstruction error 8.943264
>> Epoch 6 finished 	RBM Reconstruction error 8.386539
>> Epoch 7 finished 	RBM Reconstruction error 8.092778
>> Epoch 8 finished 	RBM

In [ ]:
#case5
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.452019
>> Epoch 2 finished 	RBM Reconstruction error 40.543458
>> Epoch 3 finished 	RBM Reconstruction error 40.711748
>> Epoch 4 finished 	RBM Reconstruction error 41.021558
>> Epoch 5 finished 	RBM Reconstruction error 41.274169
>> Epoch 6 finished 	RBM Reconstruction error 41.495661
>> Epoch 7 finished 	RBM Reconstruction error 41.789053
>> Epoch 8 finished 	RBM Reconstruction error 41.998737
>> Epoch 9 finished 	RBM Reconstruction error 42.236481
>> Epoch 10 finished 	RBM Reconstruction error 42.178893
>> Epoch 1 finished 	RBM Reconstruction error 14.061078
>> Epoch 2 finished 	RBM Reconstruction error 10.807890
>> Epoch 3 finished 	RBM Reconstruction error 9.859759
>> Epoch 4 finished 	RBM Reconstruction error 9.207584
>> Epoch 5 finished 	RBM Reconstruction error 8.653982
>> Epoch 6 finished 	RBM Reconstruction error 8.070736
>> Epoch 7 finished 	RBM Reconstruction error 7.613231
>> Epoch 8 finished 	RBM 

In [ ]:
#case6
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification

dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)

le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.850058
>> Epoch 2 finished 	RBM Reconstruction error 40.894614
>> Epoch 3 finished 	RBM Reconstruction error 40.964123
>> Epoch 4 finished 	RBM Reconstruction error 41.160024
>> Epoch 5 finished 	RBM Reconstruction error 41.381316
>> Epoch 6 finished 	RBM Reconstruction error 41.600540
>> Epoch 7 finished 	RBM Reconstruction error 41.795998
>> Epoch 8 finished 	RBM Reconstruction error 42.015733
>> Epoch 9 finished 	RBM Reconstruction error 42.387931
>> Epoch 10 finished 	RBM Reconstruction error 42.106841
>> Epoch 1 finished 	RBM Reconstruction error 14.815408
>> Epoch 2 finished 	RBM Reconstruction error 11.054120
>> Epoch 3 finished 	RBM Reconstruction error 10.096250
>> Epoch 4 finished 	RBM Reconstruction error 9.336926
>> Epoch 5 finished 	RBM Reconstruction error 8.701862
>> Epoch 6 finished 	RBM Reconstruction error 8.046473
>> Epoch 7 finished 	RBM Reconstruction error 7.714260
>> Epoch 8 finished 	RBM

In [ ]:
#case 7
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.611068
>> Epoch 2 finished 	RBM Reconstruction error 42.323009
>> Epoch 3 finished 	RBM Reconstruction error 42.124878
>> Epoch 4 finished 	RBM Reconstruction error 42.228901
>> Epoch 5 finished 	RBM Reconstruction error 42.515722
>> Epoch 6 finished 	RBM Reconstruction error 42.770853
>> Epoch 7 finished 	RBM Reconstruction error 42.997237
>> Epoch 8 finished 	RBM Reconstruction error 43.172563
>> Epoch 9 finished 	RBM Reconstruction error 43.458511
>> Epoch 10 finished 	RBM Reconstruction error 43.307241
>> Epoch 1 finished 	RBM Reconstruction error 9.489080
>> Epoch 2 finished 	RBM Reconstruction error 6.303519
>> Epoch 3 finished 	RBM Reconstruction error 5.026020
>> Epoch 4 finished 	RBM Reconstruction error 4.575114
>> Epoch 5 finished 	RBM Reconstruction error 4.419034
>> Epoch 6 finished 	RBM Reconstruction error 4.197204
>> Epoch 7 finished 	RBM Reconstruction error 4.079415
>> Epoch 8 finished 	RBM Re

In [ ]:
#case 8
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.862700
>> Epoch 2 finished 	RBM Reconstruction error 43.131203
>> Epoch 3 finished 	RBM Reconstruction error 43.034387
>> Epoch 4 finished 	RBM Reconstruction error 43.150786
>> Epoch 5 finished 	RBM Reconstruction error 43.268527
>> Epoch 6 finished 	RBM Reconstruction error 43.463622
>> Epoch 7 finished 	RBM Reconstruction error 43.633679
>> Epoch 8 finished 	RBM Reconstruction error 43.762163
>> Epoch 9 finished 	RBM Reconstruction error 44.120498
>> Epoch 10 finished 	RBM Reconstruction error 44.008004
>> Epoch 1 finished 	RBM Reconstruction error 11.074246
>> Epoch 2 finished 	RBM Reconstruction error 7.542301
>> Epoch 3 finished 	RBM Reconstruction error 5.969889
>> Epoch 4 finished 	RBM Reconstruction error 5.339882
>> Epoch 5 finished 	RBM Reconstruction error 5.073346
>> Epoch 6 finished 	RBM Reconstruction error 4.748718
>> Epoch 7 finished 	RBM Reconstruction error 4.537777
>> Epoch 8 finished 	RBM R

In [ ]:
#case 9
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.231257
>> Epoch 2 finished 	RBM Reconstruction error 42.375992
>> Epoch 3 finished 	RBM Reconstruction error 42.243234
>> Epoch 4 finished 	RBM Reconstruction error 42.214945
>> Epoch 5 finished 	RBM Reconstruction error 42.350674
>> Epoch 6 finished 	RBM Reconstruction error 42.420852
>> Epoch 7 finished 	RBM Reconstruction error 42.563558
>> Epoch 8 finished 	RBM Reconstruction error 42.631410
>> Epoch 9 finished 	RBM Reconstruction error 42.861455
>> Epoch 10 finished 	RBM Reconstruction error 42.754961
>> Epoch 1 finished 	RBM Reconstruction error 9.733202
>> Epoch 2 finished 	RBM Reconstruction error 6.367573
>> Epoch 3 finished 	RBM Reconstruction error 5.268157
>> Epoch 4 finished 	RBM Reconstruction error 4.822360
>> Epoch 5 finished 	RBM Reconstruction error 4.627028
>> Epoch 6 finished 	RBM Reconstruction error 4.419239
>> Epoch 7 finished 	RBM Reconstruction error 4.263068
>> Epoch 8 finished 	RBM Re

In [ ]:
#case 10
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.780271
>> Epoch 2 finished 	RBM Reconstruction error 40.872977
>> Epoch 3 finished 	RBM Reconstruction error 41.017986
>> Epoch 4 finished 	RBM Reconstruction error 41.373823
>> Epoch 5 finished 	RBM Reconstruction error 41.698571
>> Epoch 6 finished 	RBM Reconstruction error 41.948013
>> Epoch 7 finished 	RBM Reconstruction error 42.196067
>> Epoch 8 finished 	RBM Reconstruction error 42.439778
>> Epoch 9 finished 	RBM Reconstruction error 42.863548
>> Epoch 10 finished 	RBM Reconstruction error 42.649242
>> Epoch 1 finished 	RBM Reconstruction error 14.179907
>> Epoch 2 finished 	RBM Reconstruction error 10.724631
>> Epoch 3 finished 	RBM Reconstruction error 9.625305
>> Epoch 4 finished 	RBM Reconstruction error 8.980324
>> Epoch 5 finished 	RBM Reconstruction error 8.484160
>> Epoch 6 finished 	RBM Reconstruction error 7.885944
>> Epoch 7 finished 	RBM Reconstruction error 7.560121
>> Epoch 8 finished 	RBM 

In [ ]:
#case 11
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.792308
>> Epoch 2 finished 	RBM Reconstruction error 40.697907
>> Epoch 3 finished 	RBM Reconstruction error 40.745301
>> Epoch 4 finished 	RBM Reconstruction error 40.877579
>> Epoch 5 finished 	RBM Reconstruction error 41.123398
>> Epoch 6 finished 	RBM Reconstruction error 41.327932
>> Epoch 7 finished 	RBM Reconstruction error 41.602009
>> Epoch 8 finished 	RBM Reconstruction error 41.763390
>> Epoch 9 finished 	RBM Reconstruction error 42.133638
>> Epoch 10 finished 	RBM Reconstruction error 41.999716
>> Epoch 1 finished 	RBM Reconstruction error 13.749287
>> Epoch 2 finished 	RBM Reconstruction error 10.896676
>> Epoch 3 finished 	RBM Reconstruction error 10.036325
>> Epoch 4 finished 	RBM Reconstruction error 9.319138
>> Epoch 5 finished 	RBM Reconstruction error 8.862726
>> Epoch 6 finished 	RBM Reconstruction error 8.321328
>> Epoch 7 finished 	RBM Reconstruction error 7.879983
>> Epoch 8 finished 	RBM

In [ ]:
#case 12
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])

X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.928273
>> Epoch 2 finished 	RBM Reconstruction error 41.062688
>> Epoch 3 finished 	RBM Reconstruction error 41.101849
>> Epoch 4 finished 	RBM Reconstruction error 41.365208
>> Epoch 5 finished 	RBM Reconstruction error 41.580365
>> Epoch 6 finished 	RBM Reconstruction error 41.780221
>> Epoch 7 finished 	RBM Reconstruction error 41.989691
>> Epoch 8 finished 	RBM Reconstruction error 42.163667
>> Epoch 9 finished 	RBM Reconstruction error 42.410279
>> Epoch 10 finished 	RBM Reconstruction error 42.337359
>> Epoch 1 finished 	RBM Reconstruction error 14.425925
>> Epoch 2 finished 	RBM Reconstruction error 10.897882
>> Epoch 3 finished 	RBM Reconstruction error 9.837923
>> Epoch 4 finished 	RBM Reconstruction error 9.177402
>> Epoch 5 finished 	RBM Reconstruction error 8.672123
>> Epoch 6 finished 	RBM Reconstruction error 8.027297
>> Epoch 7 finished 	RBM Reconstruction error 7.678715
>> Epoch 8 finished 	RBM 

In [ ]:
#case 13
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.996420
>> Epoch 2 finished 	RBM Reconstruction error 42.872291
>> Epoch 3 finished 	RBM Reconstruction error 42.578621
>> Epoch 4 finished 	RBM Reconstruction error 42.563326
>> Epoch 5 finished 	RBM Reconstruction error 42.745222
>> Epoch 6 finished 	RBM Reconstruction error 42.918616
>> Epoch 7 finished 	RBM Reconstruction error 43.089202
>> Epoch 8 finished 	RBM Reconstruction error 43.303874
>> Epoch 9 finished 	RBM Reconstruction error 43.557284
>> Epoch 10 finished 	RBM Reconstruction error 43.464297
>> Epoch 1 finished 	RBM Reconstruction error 9.802981
>> Epoch 2 finished 	RBM Reconstruction error 6.206737
>> Epoch 3 finished 	RBM Reconstruction error 4.927590
>> Epoch 4 finished 	RBM Reconstruction error 4.479526
>> Epoch 5 finished 	RBM Reconstruction error 4.279783
>> Epoch 6 finished 	RBM Reconstruction error 4.175113
>> Epoch 7 finished 	RBM Reconstruction error 3.988726
>> Epoch 8 finished 	RBM Re

>> Epoch 99 finished 	ANN training loss 0.894456
[END] Fine tuning step

Accuracy: 0.617647
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  2  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  5  0  2  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 10  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  1  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 14  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  5  0  0  0  4  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  7  2]
 [ 0  2  0  0  0  0  0  0

In [ ]:
#case 14
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.609389
>> Epoch 2 finished 	RBM Reconstruction error 42.852918
>> Epoch 3 finished 	RBM Reconstruction error 42.818830
>> Epoch 4 finished 	RBM Reconstruction error 42.948735
>> Epoch 5 finished 	RBM Reconstruction error 43.098784
>> Epoch 6 finished 	RBM Reconstruction error 43.210891
>> Epoch 7 finished 	RBM Reconstruction error 43.344079
>> Epoch 8 finished 	RBM Reconstruction error 43.456196
>> Epoch 9 finished 	RBM Reconstruction error 43.823303
>> Epoch 10 finished 	RBM Reconstruction error 43.657357
>> Epoch 1 finished 	RBM Reconstruction error 10.006001
>> Epoch 2 finished 	RBM Reconstruction error 6.766770
>> Epoch 3 finished 	RBM Reconstruction error 5.402900
>> Epoch 4 finished 	RBM Reconstruction error 4.843395
>> Epoch 5 finished 	RBM Reconstruction error 4.601433
>> Epoch 6 finished 	RBM Reconstruction error 4.367920
>> Epoch 7 finished 	RBM Reconstruction error 4.198896
>> Epoch 8 finished 	RBM R


Accuracy: 0.563725
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  4  0  3  0  0  0  0  0  0  0  1  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  4  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  6  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  2  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  1  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  9  0]
 [ 0  2  0  0  0  0  0  0  1  0  0  1  0  0  0  7  4]]


In [ ]:
#case 15
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[128, 128, 128, 128, 128, 128],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 43.886352
>> Epoch 2 finished 	RBM Reconstruction error 43.046046
>> Epoch 3 finished 	RBM Reconstruction error 42.805803
>> Epoch 4 finished 	RBM Reconstruction error 42.905842
>> Epoch 5 finished 	RBM Reconstruction error 43.020510
>> Epoch 6 finished 	RBM Reconstruction error 43.075038
>> Epoch 7 finished 	RBM Reconstruction error 43.240156
>> Epoch 8 finished 	RBM Reconstruction error 43.335682
>> Epoch 9 finished 	RBM Reconstruction error 43.542940
>> Epoch 10 finished 	RBM Reconstruction error 43.468387
>> Epoch 1 finished 	RBM Reconstruction error 11.087082
>> Epoch 2 finished 	RBM Reconstruction error 7.220903
>> Epoch 3 finished 	RBM Reconstruction error 5.597691
>> Epoch 4 finished 	RBM Reconstruction error 4.919397
>> Epoch 5 finished 	RBM Reconstruction error 4.708293
>> Epoch 6 finished 	RBM Reconstruction error 4.420802
>> Epoch 7 finished 	RBM Reconstruction error 4.239472
>> Epoch 8 finished 	RBM R


Accuracy: 0.495098
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0]
 [ 0  2  0  2  0  3  0  0  0  0  0  0  0  3  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  3  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  1  2  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  7  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  8  1]
 [ 0  2  0  0  0  0  0  4  1  0  0  1  0  0  0  6  1]]


In [ ]:
#case 16
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.05)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.881581
>> Epoch 2 finished 	RBM Reconstruction error 41.257958
>> Epoch 3 finished 	RBM Reconstruction error 41.323386
>> Epoch 4 finished 	RBM Reconstruction error 41.571337
>> Epoch 5 finished 	RBM Reconstruction error 41.877749
>> Epoch 6 finished 	RBM Reconstruction error 42.132660
>> Epoch 7 finished 	RBM Reconstruction error 42.289599
>> Epoch 8 finished 	RBM Reconstruction error 42.371411
>> Epoch 9 finished 	RBM Reconstruction error 42.527196
>> Epoch 10 finished 	RBM Reconstruction error 42.431652
>> Epoch 1 finished 	RBM Reconstruction error 14.721472
>> Epoch 2 finished 	RBM Reconstruction error 11.279943
>> Epoch 3 finished 	RBM Reconstruction error 10.174998
>> Epoch 4 finished 	RBM Reconstruction error 9.224299
>> Epoch 5 finished 	RBM Reconstruction error 8.430844
>> Epoch 6 finished 	RBM Reconstruction error 7.848715
>> Epoch 7 finished 	RBM Reconstruction error 7.580234
>> Epoch 8 finished 	RBM

>> Epoch 99 finished 	ANN training loss 0.204403
[END] Fine tuning step

Accuracy: 0.901961
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  2  0  9  0]
 [ 0  0  0  0  0  0  0  0

In [ ]:
#case 17
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.1)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.792575
>> Epoch 2 finished 	RBM Reconstruction error 40.771735
>> Epoch 3 finished 	RBM Reconstruction error 40.879275
>> Epoch 4 finished 	RBM Reconstruction error 41.065100
>> Epoch 5 finished 	RBM Reconstruction error 41.151779
>> Epoch 6 finished 	RBM Reconstruction error 41.341957
>> Epoch 7 finished 	RBM Reconstruction error 41.493800
>> Epoch 8 finished 	RBM Reconstruction error 41.654394
>> Epoch 9 finished 	RBM Reconstruction error 41.835950
>> Epoch 10 finished 	RBM Reconstruction error 41.851513
>> Epoch 1 finished 	RBM Reconstruction error 14.581966
>> Epoch 2 finished 	RBM Reconstruction error 11.285711
>> Epoch 3 finished 	RBM Reconstruction error 10.320870
>> Epoch 4 finished 	RBM Reconstruction error 9.670917
>> Epoch 5 finished 	RBM Reconstruction error 9.090603
>> Epoch 6 finished 	RBM Reconstruction error 8.423300
>> Epoch 7 finished 	RBM Reconstruction error 8.043951
>> Epoch 8 finished 	RBM

>> Epoch 99 finished 	ANN training loss 0.333221
[END] Fine tuning step

Accuracy: 0.857843
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0 12  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  1  0  0  0  8  0  2]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  2  0  8  1]
 [ 0  0  1  0  0  0  0  0

In [ ]:
#case 18
import numpy as np
import pandas as pd
np.random.seed(3529)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from dbn.tensorflow import SupervisedDBNClassification


dataset = pd.read_csv("Instruments.csv")
dataset = dataset.drop(["File Name"], axis=1)


le = LabelEncoder()
dataset['Instrument'] = le.fit_transform(dataset['Instrument'])


X = np.array(dataset.drop(["Instrument"], axis=1))
Y = np.array(dataset.Instrument.values)

ss=StandardScaler()
X = ss.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

classifier = SupervisedDBNClassification(hidden_layers_structure=[256, 256, 256, 256, 256, 256],
                                         learning_rate_rbm=0.05,
                                         learning_rate=0.4,
                                         n_epochs_rbm=10,
                                         n_iter_backprop=100,
                                         batch_size=32,
                                         activation_function='sigmoid',
                                         dropout_p=0.2)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print('\nAccuracy: %f' % accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 41.372756
>> Epoch 2 finished 	RBM Reconstruction error 40.476467
>> Epoch 3 finished 	RBM Reconstruction error 40.702153
>> Epoch 4 finished 	RBM Reconstruction error 41.071466
>> Epoch 5 finished 	RBM Reconstruction error 41.296782
>> Epoch 6 finished 	RBM Reconstruction error 41.597052
>> Epoch 7 finished 	RBM Reconstruction error 41.837017
>> Epoch 8 finished 	RBM Reconstruction error 42.108080
>> Epoch 9 finished 	RBM Reconstruction error 42.290347
>> Epoch 10 finished 	RBM Reconstruction error 42.388742
>> Epoch 1 finished 	RBM Reconstruction error 14.298517
>> Epoch 2 finished 	RBM Reconstruction error 11.045434
>> Epoch 3 finished 	RBM Reconstruction error 9.978397
>> Epoch 4 finished 	RBM Reconstruction error 9.239408
>> Epoch 5 finished 	RBM Reconstruction error 8.596379
>> Epoch 6 finished 	RBM Reconstruction error 7.899508
>> Epoch 7 finished 	RBM Reconstruction error 7.500735
>> Epoch 8 finished 	RBM 

>> Epoch 99 finished 	ANN training loss 0.551749
[END] Fine tuning step

Accuracy: 0.843137
Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  1  0  1  0  0  0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  6  0  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  8  1]
 [ 0  0  0  0  0  0  0  0